#!/usr/bin/env bash
# Configure your domain zone so that the subdomain www points to your load-balancer IP (lb-01)
# Let’s also add other subdomains to make our life easier, and write a Bash script 
# that will display information about subdomains.

domain=$1
subdomain=$2

if [ -z "$subdomain" ]; then
  subdomains=("www" "lb-01" "web-01" "web-02")
else
  subdomains=("$subdomain")
fi

for sub in "${subdomains[@]}"; do
  record_type=$(dig +short "$sub.$domain" | awk '{print $4}')
  destination=$(dig +short "$sub.$domain" | awk '{print $1}')
  echo "The subdomain $sub is a $record_type record and points to $destination"
done
