#!/usr/bin/env bash
#Install nginx web server

# Update package list
apt-get update

# Install Nginx
apt-get -y install nginx

# Create a file with "Hello World!" message
echo "Hello World!" > /var/www/html/index.html

# Restart Nginx
service nginx restart
