#!/usr/bin/env bash
#Install nginx web server

# Update package list
sudo apt-get update

# Install Nginx
sudo apt-get install nginx -y

# Restart Nginx
sudo service nginx restart

# Create a file with "Hello World!" message
echo "Hello World!" > /var/www/html/index.html
