#!/usr/bin/env bash
#Configuring  Nginx server so that redirect_me is redirecting to another page

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
my_new_stringt="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.alex.com permanent;"
sudo sed -i "s/server_name _;/$my_new_string/" /etc/nginx/sites-enabled/default

sudo service nginx restart
