#!/usr/bin/env bash
#Configuring  Nginx server so that redirect_me is redirecting to another page

sudo apt-get update
sudo apt-get install nginx -y
sudo systemctl start nginx
sudo systemctl enable nginx
sudo echo "server {
    listen 80;
    listen [::]:80;
    server_name _;
    return 301 https://www.newsite.com$request_uri;
}" > /etc/nginx/sites-available/redirect_me.conf
sudo ln -s /etc/nginx/sites-available/redirect_me.conf /etc/nginx/sites-enabled/
sudo systemctl restart nginx
