#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)

sudo apt update
sudo apt install nginx

# Right now, we will only need to allow traffic on port 80
sudo ufw allow 'Nginx HTTP'

add_header X-Served-By $hostname
