#!/usr/bin/env bash
# Bash script that generates a MySQL dump and creates a compressed archive out of it

# Create backup directory
mkdir -p /backup/mysql

# Dump MySQL databases
mysqldump -u root -p"$1" --all-databases > /backup/mysql/backup.sql

# Compress backup file
tar -czvf $(date +%d-%m-%Y).tar.gz /backup/mysql/backup.sql
