#!/usr/bin/env bash
# Bash script that generates a MySQL dump and creates a compressed archive out of it

# Dump MySQL databases
mysqldump -uroot -p"$1" --all-databases > backup.sql

# Compress backup file
tar -czvf $(date +%d-%m-%Y).tar.gz backup.sql
