#!/usr/bin/env bash
# Manage my process

instruct="$1"

if [ -z "$instruct" ]; then
  echo "Usage: manage_my_process {start|stop|restart}"
  exit
fi

if [ "$instruct" == "start" ]; then

  bash ./manage_my_process &
  echo "$!" > /var/run/my_process.pid
  echo "manage_my_process started"

elif [ "$instruct" == "stop" ]; then
  [ -e "/var/run/my_process.pid" ] && pkill -f './manage_my_process' && rm /var/run/my_process.pid
  echo "manage_my_process stopped"

elif [ "$instruct" == "restart" ]; then

  "$0" stop >& /dev/null
  "$0" start >& /dev/null
  echo "manage_my_process restarted"

else
  echo "Usage: manage_my_process {start|stop|restart}" 
fi
