#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd, using the while loop + IFS

data="/etc/passwd"

while IFS= read -r ln; do
  user_name=$(echo "$ln" | cut -d ':' -f1)
  group_id=$(echo "$ln" | cut -d ':' -f4)
  directory=$(echo "$ln" | cut -d ':' -f6)
  shell=$(echo "$ln" | cut -d ':' -f7)
  user_id=$(echo "$ln" | cut -d ':' -f3)
  password=$(echo "$ln" | cut -d ':' -f2)
  info=$(echo "$ln" | cut -d ':' -f5)

  echo "The user $user_name is part of the $group_id gang, lives in $directory and rides $shell. $user_id's place is protected by the passcode $password, more info about the user here: $info"
done < "$data"

