#!/usr/bin/env bash
# Bash script that gives you information about the school file

data="school"

if [ -e "$data" ]; then

  echo "school file exists"

  if [ ! -s "$data" ]; then
    echo "school file is empty"

    if [ -f "$data" ]; then
      echo "school is a regular file"
    fi  

  else

    echo "school file is not empty"

    if [ -f "$data" ]; then
      echo "school is a regular file"
    fi  
  
  fi

else
  
  echo "school file does not exist"

fi
