#!/usr/bin/env bash
# nginx must be running as nginx user
# nginx must be listening on all active IPs on port 8080
# You cannot use apt-get remove

pkill apache2
sed -i "s/user www-data/user nginx/g" /etc/nginx/nginx.conf
sed -i "s80/8080/g" /etc/nginx/sites-available/default
# Restart nginx
sudo -u gninx service nginx restart
