#!/usr/bin/env bash
# Using what you did for task #1, make your fix short and sweet.

pkill -f apache2
sed -i "s/#user www-data/user nginx/g" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
