#!/usr/bin/env bash
#Your machine has an SSH configuration file for the local SSH client,
#let’s configure it to our needs so that you can connect to a server without typing a password.

Host ubuntu
	HostName 18.234.192.200
	User ubuntu
	IdentityFile ~/.ssh/school
	PasswordAuthentication no
